### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Militia21** [yeetedmeme/kaspammer#4]
body-parser deprecated undefined extended: provide extended option server.js:20:17
Your app is listening on port 44067
Error: ENOENT: no such file or directory, stat '/home/runner/kaspammerindex.html'

I get these errors

**Comment by yeetedmeme** [comment]
there is not file called "kaspammerindex.html" you must have edited something.

**Comment by Militia21** [comment]
but in the fork there was no kaspammerindex.html

**Comment by yeetedmeme** [comment]
It would seem that this is a problem on your end, not mine. Reopen this issue if you need anything else.
